### ISSUE TITLE
Adding "Benchmark" and "Pre-trained BERT models"

### ISSUE THREAD

**Issue by gentaiscool** [louisowen6/NLP_bahasa_resources#3]
I want to propose two new sections for this repo:
1) Benchmarks
probably we can add IndoNLU https://github.com/indobenchmark/indonlu and 
2) Pre-trained contextual models 
we can add HuggingFace links of IndoBERT models. 

What do you think?

**Comment by louisowen6** [comment]
Sure thing! Thanks for sharing @gentaiscool
